### ISSUE TITLE
/caches endpoint missing when migrated from 1.37 to 2.2.1

### ISSUE THREAD

**Issue by webkitez** [micronaut-projects/micronaut-cache#263]
Thanks for reporting an issue, please review the task list below before submitting the
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Stack Overflow (https://stackoverflow.com/tags/micronaut) or Gitter (https://gitter.im/micronautfw/). DO NOT use the issue tracker to ask questions.

### Task List

- [X] Steps to reproduce provide
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

clone the repo and run ./gradlew run https://github.com/webkitez/micronaut-cache

### Expected Behaviour

 Cannot see /caches endpoint which used to come in1.37.Have added managaement dependecies too. and enabled in application.yml

Tell us what should happen

### Actual Behaviour

Tell us what happens instead

### Environment Information

- **Operating System**: macOS catalina 10.15.7
- **Micronaut Version:** 2.2.1
- **JDK Version:**  openjdk version "11.0.6" 2020-01-14

### Example Application

- https://github.com/webkitez/micronaut-cache

**Comment by alvarosanchez** [comment]
You need to add the dependency `io.micronaut.cache:micronaut-cache-management`

**Comment by webkitez** [comment]
oh yes .. should we update the doc..it no where says that dependency to be added.. does it?

**Comment by alvarosanchez** [comment]
It is documented, but there hasn't been a release since then, so it's only in the snapshot docs: https://micronaut-projects.github.io/micronaut-cache/snapshot/guide/#endpoint

That said, it does not mention the dependency, so I will create an issue for adding that.

**Comment by alvarosanchez** [comment]
Actually I just edited the docs: https://github.com/micronaut-projects/micronaut-cache/commit/b41f8bc04e5db46708167ea8d439b953f0b192ad

**Comment by webkitez** [comment]
Thanks for quick response. Also surprisingly cache-management pulls the main management dependency(https://github.com/micronaut-projects/micronaut-cache/blob/master/cache-management/build.gradle#L3)  which enables other endpoints like beans,info,health. Is it by design we wanted to keep this out of main management dependency ?

**Comment by alvarosanchez** [comment]
Unfortunately, there is no other way. `io.micronaut:micronaut-management` contains both annotations such as `io.micronaut.management.endpoint.annotation.Endpoint`, as well as the implementations you mentioned.

You can disable via configuration the endpoints you don't want, however.
